package Códigos;


public class Tela_Principal extends javax.swing.JFrame {

   
    public Tela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_azul = new javax.swing.JPanel();
        lbl_icone = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_txtWilhams1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_entrar2 = new javax.swing.JLabel();
        pnl_verde = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txt_senha = new javax.swing.JPasswordField();
        lbl_senha = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_email2 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_nome = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        lbl_membro = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_entrar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_azul.setBackground(new java.awt.Color(0, 153, 153));

        lbl_icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ícones/Icon PNG.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lbl_txtWilhams1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_txtWilhams1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl_txtWilhams1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txtWilhams1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_txtWilhams1.setText("CRIADO BY WILHAMS GOMES");

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_entrar2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_entrar2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_entrar2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_entrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_entrar2.setText("JÁ TENHO UMA CONTA");
        lbl_entrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(lbl_entrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 182, 28));

        javax.swing.GroupLayout pnl_azulLayout = new javax.swing.GroupLayout(pnl_azul);
        pnl_azul.setLayout(pnl_azulLayout);
        pnl_azulLayout.setHorizontalGroup(
            pnl_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, pnl_azulLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lbl_icone)
                .addGap(118, 118, 118))
            .addGroup(pnl_azulLayout.createSequentialGroup()
                .addGroup(pnl_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_azulLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, pnl_azulLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lbl_txtWilhams1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(81, 81, 81))
        );
        pnl_azulLayout.setVerticalGroup(
            pnl_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_azulLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbl_txtWilhams1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_icone, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2)
                .addGap(49, 49, 49)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pnl_verde.setBackground(new java.awt.Color(0, 51, 51));
        pnl_verde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setBackground(new java.awt.Color(255, 255, 255));
        lbl_title.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("INFORME SEUS DADOS");
        pnl_verde.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 180, 33));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        pnl_verde.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 140, 14));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        pnl_verde.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 240, 291, 14));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        pnl_verde.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 317, 291, 14));

        txt_senha.setBackground(new java.awt.Color(0, 51, 51));
        txt_senha.setForeground(new java.awt.Color(255, 255, 255));
        txt_senha.setText("jPasswordField1");
        txt_senha.setBorder(null);
        pnl_verde.add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 291, 31));

        lbl_senha.setBackground(new java.awt.Color(255, 255, 255));
        lbl_senha.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_senha.setText("PASSWORD");
        pnl_verde.add(lbl_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 27));

        lbl_name.setBackground(new java.awt.Color(255, 255, 255));
        lbl_name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("NAME");
        pnl_verde.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 180, 27));

        lbl_email2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_email2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_email2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email2.setText("EMAIL");
        pnl_verde.add(lbl_email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, 27));

        txt_email.setBackground(new java.awt.Color(0, 51, 51));
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setText("Digite seu email");
        txt_email.setBorder(null);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        pnl_verde.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 290, 30));

        txt_nome.setBackground(new java.awt.Color(0, 51, 51));
        txt_nome.setForeground(new java.awt.Color(255, 255, 255));
        txt_nome.setText("Digite seu nome");
        txt_nome.setBorder(null);
        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });
        pnl_verde.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 290, 30));

        jCheckBox1.setBackground(new java.awt.Color(0, 51, 51));
        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Aceitos os termos da plataforma");
        jCheckBox1.setBorder(null);
        pnl_verde.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 240, -1));

        lbl_membro.setBackground(new java.awt.Color(255, 255, 255));
        lbl_membro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_membro.setForeground(new java.awt.Color(255, 255, 255));
        lbl_membro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_membro.setText("SEJA UM MEMBRO");
        lbl_membro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_verde.add(lbl_membro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 140, 27));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        pnl_verde.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 149, 291, 14));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_entrar1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_entrar1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_entrar1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_entrar1.setText("ACESSAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_entrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_entrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_verde.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_azul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnl_verde, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_verde, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnl_azul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
       
        txt_nome.setText("");
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
       txt_email.setText("");
    }//GEN-LAST:event_txt_emailActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
       
        Tela_Login obj = new Tela_Login();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel4MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_email2;
    private javax.swing.JLabel lbl_entrar1;
    private javax.swing.JLabel lbl_entrar2;
    private javax.swing.JLabel lbl_icone;
    private javax.swing.JLabel lbl_membro;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_txtWilhams1;
    private javax.swing.JPanel pnl_azul;
    private javax.swing.JPanel pnl_verde;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables
}
